config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  get 'daily_challenges/index'
  get 'password_resets/new'
  get 'password_resets/ed'
  get 'password_resets/it'
  get 'sessions/new'
  get 'users/new'
  get 'users/:id/private_post', to: 'users#private_post'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'search', to:'users#search'
  patch "challenge", to:'users#dailyChallenge'
  patch "track", to:'daily_challenges#index'
  get "task", to:'daily_challenges#index'
  get "remainder", to:'users#addRemainderToQueue'
  get "activities", to:'activities#index'
  get 'search_by_tag', to:'users#search_activities'
  get 'search_user', to:'users#search_user'
  get 'challenges', to:'challenge_users#show'
  get '/test', to: 'static_pages#test'
  get '/challenge_user', to: 'challenges#challenge_user'
  get '/my_challenges', to: 'challenges#show'
  post '/search_user', to: 'challenge_users#create'
  delete '/search_user', to: 'challenge_users#destroy'
  delete '/my_challenges', to: 'challenges#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :activities
  resources :comments
  resources :challenges
  resources :reactions, only: [ :create, :destroy ]
  resources :haiku_reactions, only: [:create, :destroy, :edit]
  resources :microposts, only: [ :create, :destroy ]
  resources :haikus, only: [ :create, :destroy, :update, :show ]
  resources :relationships, only: [:create, :destroy]
  resources :haiku_comments
  resources :daily_challenges
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :notifications
end

app/models/haiku.rb
class HaikuValidator < ActiveModel::Validator
  include HaikusHelper
  def validate(record)
    if record.verse_1 && !verse_1_haiku?(record.verse_1)
      record.errors.add :base, "First verse should be exactly 5 syllabes but found #{SyllableCount(record.verse_1)}"
    end
    if record.verse_2 && !verse_2_haiku?(record.verse_2)
      record.errors.add :base, "Second verse should be exactly 7 syllabes but found #{SyllableCount(record.verse_2)}"
    end
    if record.verse_3 && !verse_3_haiku?(record.verse_3)
      record.errors.add :base, "Third verse should be exactly 5 syllabes but found #{SyllableCount(record.verse_3)}"
    end
  end
end
class Haiku < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->(controller, model){ controller && controller.current_user}
  belongs_to :user
  has_one_attached :image
  validates :user_id, presence: true
  validates :verse_1, presence: true, length: { maximum: 40 }
  validates :verse_2, presence: true, length: { maximum: 40 }
  validates :verse_3, presence: true, length: { maximum: 40 }
  validates :tag, length: { maximum: 15 }
  has_many :haiku_comments, dependent: :destroy
  # has_many :daily_challenges, dependent: :destroy
  has_many :haiku_reactions, dependent: :destroy

  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" }, size: { less_than: 5.megabytes, message: "should be less than 5MB" }

  validates_with HaikuValidator

  default_scope -> { order(created_at: :desc) }

  def display_image
    image.variant(resize_to_limit: [500, 500])
 
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
    include HaikusHelper
    before_action :logged_in_user, only: [:create, :destroy, :update]
    before_action :correct_user, only: [:destroy, :update]

    def create
        verse_1 = params[:haiku][:verse_1]
        verse_2 = params[:haiku][:verse_2]
        verse_3 = params[:haiku][:verse_3]
        tag = params[:haiku][:tag]
        bgcolor = params[:haiku][:bgcolor]
        if(params[:post_button] == "Post")
            is_public = true
            if params[:visibility] && params[:visibility] === 'Private'
                is_public = false
            end

            @haiku = current_user.haikus.build(verse_1: verse_1, verse_2: verse_2, verse_3: verse_3,tag: tag, public: is_public, bgcolor: bgcolor)
            @haiku.image.attach(params[:haiku][:image])
            if @haiku.save
                flash[:success] = "Haiku created!"
                # redirect_to root_url
                if current_user.challenge_mode
                  if @haiku.created_at >= current_user.challenge_start_date
                    p "haiku--------------------#{@haiku.created_at}"
                    # find the daily challenge by user_id and date
                    # update posted = tru
                    # @postedDate = DailyChallenge.where("user_id = ? and thirtyDates = ? ", current_user.id,  "2021-03-08 14:23:02.383848")
                    haikuDate = @haiku.created_at.to_date
                    @postedDate = DailyChallenge.where(user_id: current_user.id, thirtyDates: haikuDate.midnight..haikuDate.end_of_day) 
                    # @postedDate = DailyChallenge.where("user_id = ? and thirtyDates LIKE ? ", current_user.id, "%#{@haiku.created_at.to_date}%")
                    p "postedDate:#{@postedDate.length}"
                    if  @postedDate && @postedDate.length >= 0 && !@postedDate.first.postStatus?
                      @postedDate.first.update_columns(postStatus: true)
                      # @postedDate = DailyChallenge.update('postStatus').where("user_id = ? and thirtyDates = ? ", current_user.id, @haiku.created_at)
                    else
                      p "challenge column not updated"
                    end

                  end

                end
                redirect_to root_url
                #redirect_to request.referrer
              # redirect_to daily_challenges_url
            else
                @comment = Comment.new
                @haiku_comment = HaikuComment.new
                @micropost = Micropost.new

                @feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                # @haiku_feed_items = current_user.haiku_feed.paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                @haiku_feed_items = Haiku.where("public = ?", true).paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                render 'static_pages/home'
            end
        elsif(params[:post_button] == "Finish")
            is_public = true
            if params[:visibility] && params[:visibility] === 'Private'
                is_public = false
            end

            @haiku = current_user.haikus.build(verse_1: params[:haiku_verse_1], verse_2: params[:haiku_verse_2], verse_3: verse_3,tag: tag, public: is_public)
            @haiku.image.attach(params[:haiku][:image])

            if @haiku.save
                user = User.find_by(id: params[:user_id])
                flash[:success] = "Congratulation you finished challenge from #{user.name}. Haiku Created Successfully."
                challenge_user = ChallengeUser.find_by(challenge_id: params[:challenge_id], user_id: current_user.id)
                if(challenge_user)
                    challenge_user.destroy
                end
                redirect_to challenges_path
            else
                @comment = Comment.new
                @haiku_comment = HaikuComment.new
                @micropost = Micropost.new

                @feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                @haiku_feed_items = Haiku.where("public = ?", true).paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                render 'static_pages/home'
            end

        else
            @challenge = current_user.challenges.build(verse_1: verse_1, verse_2: verse_2)
            if @challenge.save
                flash[:success] = "Challenge created successfully please send challenge to users"
                redirect_to challenge_user_path
            else
                @comment = Comment.new
                @haiku_comment = HaikuComment.new
                @micropost = Micropost.new
                @feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                @haiku_feed_items = Haiku.where("public = ?", true).paginate(:page => params[:page], :per_page => 5, :total_entries => 30)
                render 'static_pages/home'
            end
        end
    end
    def update
        if !@haiku.public?
            @haiku.update(public: true)
            flash[:success] = "Your Haiku is visible for public now."
            redirect_to root_url
        else
            redirect_to request.referrer || root_url
        end
        
    end

    def show
        @haiku_comment = HaikuComment.new
        @haiku = Haiku.find(params[:id])
    end

    def destroy
        @haiku.destroy
        flash[:success] = "Haiku deleted"
        redirect_to request.referrer || root_url
    end

    private
        def haiku_params
            params.require(:haiku).permit(:verse_1, :verse_2, :verse_3, :tag, :visibility, :image, :bgcolor)
        end
        def correct_user
            @haiku = current_user.haikus.find_by(id: params[:id])
            redirect_to root_url if @haiku.nil?
        end
        def challenge_params
            params.require(:haiku).permit(:verse_1, :verse_2)
        end
end

app/helpers/haikus_helper.rb
module HaikusHelper
   
    def SyllableCount(text)
        s = "->s{s.scan(/[aiouy]+e*|e(?!d$|ly).|[td]ed|le$/).size}"
        f = eval s
        f.call(text)
    end

    def verse_1_haiku?(verse)
        SyllableCount(verse) == 5 || SyllableCount(verse) == 4 || SyllableCount(verse) == 6
    end

    def verse_2_haiku?(verse)
        SyllableCount(verse) == 7 || SyllableCount(verse) == 8 || SyllableCount(verse) == 6
    end

    def verse_3_haiku?(verse)
        SyllableCount(verse) == 5 || SyllableCount(verse) == 4 || SyllableCount(verse) == 6
    end
end

app/views/haikus/_haiku.html.erb
<div style="margin-bottom: 30px;">
  <div class="row">
    <div class="card container col-md-12" style="border:solid 1px #eee; padding: 13px;">
      <div class="card-body col-md-12">
        <div class="row">
          <h5 class="card-title">
            <%= link_to gravatar_for(haiku.user, size: 30, email: haiku.user.email), haiku.user %>
          </h5>
          <div class="col-md-8">
            <h6 class="card-subtitle  text-muted"><%= link_to haiku.user.name, haiku.user, class:"text-muted" %></h6>
            <h6 class="card-subtitle text-muted"><%= time_ago_in_words(haiku.created_at) %> </h6>
          </div>
          <div class="dropdown col-md-1">
            <span class="btn btn-secondary dropdown-toggle"  id="dropdownMenu2" data-toggle="dropdown" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
              </svg>
            </span>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li>
                <%= link_to  "View", haiku_path(haiku), class: "dropdown-item" %>
              </li>
              <% if current_user?(haiku.user) %>
                <li>
                  <%= link_to "delete", haiku, method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item"  %>
                </li>
              <% end %>
              <% if current_user?(haiku.user) && !haiku.public? %>
                <%= form_with(model: haiku, html: {method: :patch}, local: true) do |f| %>
                  <%= f.submit "Make Public", class: 'btn' %>
                <% end %>
              <% else %>
              <% end %>
            </ul>
          </div>
        </div>
        <% if  haiku.image.attached?  %>
          <div class="row haiku-image-card haiku-content" style="background-image: url(<%= url_for(haiku.display_image) %>);" >
          <% else %>
            <div class="row haiku-content" style="background: <%= haiku.bgcolor; %>" >
            <% end %>
            <div >
              <p class="card-text text-center"><%= haiku.verse_1 %></p>
              <p class="card-text text-center"><%= haiku.verse_2 %></p>
              <p class="card-text text-center"><%= haiku.verse_3 %></p>
            </div>
          </div>
          <% if haiku.tag? %>
            <h4><a href="#" class="card-link">#<%= haiku.tag %></a></h4>
          <% else %>
          <% end %>
          <div class="col-md-12" style="border-bottom:1px solid #eee; margin-bottom: 25px; margin-top: 25px"> </div>
          <div class="card-footer">
            <div class= "row">
              <div class="col-md-4">
                <% if logged_in? && current_user %>
                  <div>
                    <% if !current_user.likedComment?(haiku.id) %>
                      <%= link_to edit_haiku_reaction_path("#{haiku.id}"), class: "text-muted" do %>
                        <svg style="margin-right: 5px"  xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                          <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
                        </svg>
                      <% end %>
                      <span><%= haiku.haiku_reactions.count %></span>
                    <% else %>
                      <%= link_to current_user.haiku_reactions.find_by(haiku_id: haiku.id), method: :delete do %>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                          <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.964.22.817.533 2.512.062 4.51a9.84 9.84 0 0 1 .443-.05c.713-.065 1.669-.072 2.516.21.518.173.994.68 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.162 3.162 0 0 1-.488.9c.054.153.076.313.076.465 0 .306-.089.626-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.826 4.826 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.616.849-.231 1.574-.786 2.132-1.41.56-.626.914-1.279 1.039-1.638.199-.575.356-1.54.428-2.59z"/>
                        </svg>
                      <% end %>
                      <span><%= haiku.haiku_reactions.count %></span>
                    <% end %>
                  </div>
                <% else %>
                  <span class="text-muted"><%= pluralize(haiku.haiku_reactions.count, "Like") %></span>
                <% end %>
              </div>
              <div  class="col-md-4">
                <div class="dropdown">
                  <span  data-toggle="dropdown">
                    <svg style="margin-right: 5px"  xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share-fill" viewBox="0 0 16 16">
                      <path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5z"/>
                    </svg>
                    <span class="text-muted" >Share</span>
                  </span>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li>
                      <a class="dropdown-item" href="#">
                        <%= link_to "<svg xmlns=http://www.w3.org/2000/svg width=23 height=23 fill=currentColor class='bi bi-facebook' viewBox='0 0 16 16'><path d='M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z'/></svg> <span style='font-size: 16px; color: #888'>Share to Facebook</span>".html_safe, "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", target: "_blank", class: 'share', data: { network: 'facebook'} %>
                      </a>
                    </li>
                    <li><a class="dropdown-item" href="#">
                        <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='23' height='23' fill='currentColor' class='bi bi-twitter' viewBox='0 0 16 16'><path d='M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z'/></svg> <span style='font-size: 16px; color: #888'>Share to Twitter</span>".html_safe, "https://twitter.com/intent/tweet?original_referer=#{request.original_url}&ref_src=twsrc%5Etfw&text=Haiku%20App&tw_p=tweetbutton&url=#{request.original_url}",target: "_blank", class: 'share', data: { network: 'twitter'} %>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="col-md-4">
                  <svg style="margin-right: 5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-square-text" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                    <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                  </svg>
                  <span type="link"  class="text-muted" data-toggle="collapse" data-target=<%= "#haiku-collapse-#{haiku.id}" %>>Comments <%= haiku.haiku_comments.count %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id=<%= "haiku-collapse-#{haiku.id}" %> class="collapse">
      <% if logged_in? %>
        <%= render 'haiku_comments/haiku_comment_form', haiku_id: haiku.id %>
      <% end %>
      <% if haiku.haiku_comments.any? %>
        <ol class="microposts">
          <% haiku.haiku_comments.each do |comment|%>
            <%= render 'haiku_comments/haiku_comment', haiku_comment: comment %>
          <% end %>
        </ol>
      <% end %>
    </div>

app/views/haikus/show.html.erb
<div class="row">
  <br/>
  <br/>
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <%= render @haiku %>
  </div>
</div>