config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  get 'daily_challenges/index'
  get 'password_resets/new'
  get 'password_resets/ed'
  get 'password_resets/it'
  get 'sessions/new'
  get 'users/new'
  get 'users/:id/private_post', to: 'users#private_post'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'search', to:'users#search'
  patch "challenge", to:'users#dailyChallenge'
  patch "track", to:'daily_challenges#index'
  get "task", to:'daily_challenges#index'
  get "remainder", to:'users#addRemainderToQueue'
  get "activities", to:'activities#index'
  get 'search_by_tag', to:'users#search_activities'
  get 'search_user', to:'users#search_user'
  get 'challenges', to:'challenge_users#show'
  get '/test', to: 'static_pages#test'
  get '/challenge_user', to: 'challenges#challenge_user'
  get '/my_challenges', to: 'challenges#show'
  post '/search_user', to: 'challenge_users#create'
  delete '/search_user', to: 'challenge_users#destroy'
  delete '/my_challenges', to: 'challenges#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :activities
  resources :comments
  resources :challenges
  resources :reactions, only: [ :create, :destroy ]
  resources :haiku_reactions, only: [:create, :destroy, :edit]
  resources :microposts, only: [ :create, :destroy ]
  resources :haikus, only: [ :create, :destroy, :update, :show ]
  resources :relationships, only: [:create, :destroy]
  resources :haiku_comments
  resources :daily_challenges
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :notifications
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :haiku_reaction, optional: true
  belongs_to :haiku_comment, optional: true
  belongs_to :challenge_user, optional: true
  belongs_to :relationship, optional: true

  default_scope -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
    include SessionsHelper

    def count_notification
        count_notification = Notification::where(user_id: current_user.id, is_seen: false)
        count_notification.count
    end
    def notifications
        @notifications = Notification::where(user_id: current_user.id)
    end
end

app/views/notifications/_notification.html.erb
<% notifications.each do |notification| %>
    <li class="divider"></li>
    <% if notification.notification_type == "haiku_comment" %>
        <div style="display: flex; align-items: center; padding-left: 15px">
            <div style="">
                <%= gravatar_for notification.user, size: 30 %>
            </div>
            <div style="">
                <li><li><%= "#{notification.message}"%> 
                    <%= link_to "see post", haiku_path("#{notification.haiku_comment.haiku.id}") %>
                </li>
                <span>
                <%= time_ago_in_words(notification.created_at) %>
                </span>
            </div>
        </div>
    <% elsif notification.notification_type == "haiku_reaction" %>
        <li class="divider"></li>
        <div style="display: flex; align-items: center; padding-left: 15px">
            <div style="">
                <%= gravatar_for notification.user, size: 30 %>
            </div>
            <div style="">

                <li><%= "#{notification.message}"%>
                    <%= link_to "see post", haiku_path("#{notification.haiku_reaction.haiku.id}") %>
                </li>
                <span>
                    <%= time_ago_in_words(notification.created_at) %>
                </span>
            </div>
        </div>
        
    <% elsif notification.notification_type == "challenge_user" %>
        <li class="divider"></li>
        <div style="display: flex; align-items: center; padding-left: 15px">
            <div style="">
                <%= gravatar_for notification.user, size: 30 %>
            </div>
            <div style="">
                <li><%= "#{notification.message}"%>
                </li>
                <span>
                    <%= time_ago_in_words(notification.created_at) %>
                </span>
            </div>
        </div>
        <br/>
        <ul style="list-style: none; padding-left: 70px;">
            <li><%= notification.challenge_user.challenge.verse_1 %></li>
            <li><%= notification.challenge_user.challenge.verse_2 %></li>
            <div class="disabled" style="padding-right: 50px;">
                <input class="form-control-plaintext haiku_input_field" type="text" name="optradio" disabled>
            </div>
            <span style="text-align: right;">
                <%= link_to "Accept challenge", challenges_path %>
            </span>
        </ul>
    <% elsif notification.notification_type == "relationship" %>
        <div style="display: flex; align-items: center; padding-left: 15px">
            <div style="">
                <%= gravatar_for notification.user, size: 30 %>
            </div>
            <div style="">
                <li><%= "#{notification.message}"%></li>
                <span>
                    <%= time_ago_in_words(notification.created_at) %>
                </span>
                <span style="padding-left: 90px">
                    <%= link_to "Follow back", user_path("#{notification.relationship.follower_id}") %>
                </span>
            </div>
            
        </div>
    <% end %>
    
    
<% end %>